config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "blog_posts#index"

  resources :blog_posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @blog_posts = BlogPost.all
  end

  def show
    @blog_post = BlogPost.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_params)

    if @blog_post.save
      redirect_to @blog_post
    else
      render 'new'
    end

  end

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def update
    @blog_post = BlogPost.find(params[:id])

    if @blog_post.update(blog_params)
      redirect_to @blog_post
    else
      render 'edit'
    end

  end

  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_params
    params.require(:blog_post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/edit.html.erb
<h1>Editing: <%= @blog_post.title %> </h1>

<%= form_with model: @blog_post do |form| %>
    <% if form.object.errors.any? %>
        <div>
            <% form.object.errors.full_messages.each do |msg| %>
                <div><%= msg %></div>
            <% end %>
        </div>
    <% end %>
    
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>


    <div>
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>

    <%= form.button "Submit" %>

<% end %>

app/views/blog_posts/index.html.erb
<h1>All Blogs</h1>
<%= link_to "Create New Blog Post", new_blog_post_path %>

<% @blog_posts.each do |blog_post| %>
    <div>
        <h2><%= link_to blog_post.title, blog_post_path(blog_post) %></h2>
        <%= blog_post.body %>
    </div>
<% end %>

app/views/blog_posts/new.html.erb
<h1>Create A New Blog Post</h1>

<%= form_with model: @blog_post do |form| %>
    <% if form.object.errors.any? %>
        <div>
            <% form.object.errors.full_messages.each do |msg| %>
                <div><%= msg %></div>
            <% end %>
        </div>
    <% end %>
    
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>


    <div>
        <%= form.label :body %>
        <%= form.text_area :body %>
    </div>

    <%= form.button "Submit" %>

<% end %>

app/views/blog_posts/show.html.erb
<%= link_to "Return to All Blogs", root_path %>

<h1>Viewing: <%= @blog_post.title %> </h1>
<p><%= @blog_post.body %></p>

<%= link_to "Edit", edit_blog_post_path(@blog_post) %>
<%= button_to "Delete", blog_post_path(@blog_post), method: :delete, data: {turbo_confirm: "Are You Sure"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div>
      <% if user_signed_in?  %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete  %>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>